Repository prgrms-web-devcourse-final-project/WEB6_8_CGNS_BE, pull requests merged in 2025-09, with the labels that each got.

#25 feat(be): weatherTool, ChatController 빨간줄 주석처리
  src/main/kotlin/com/back/koreaTravelGuide/domain/ai/aiChat/controller/ChatController.kt
  src/main/kotlin/com/back/koreaTravelGuide/domain/ai/aiChat/tool/WeatherTool.kt
  src/main/kotlin/com/back/koreaTravelGuide/domain/ai/weather/client/WeatherApiClient.kt
  src/main/kotlin/com/back/koreaTravelGuide/domain/ai/weather/client/tools/Tools.kt
  src/main/kotlin/com/back/koreaTravelGuide/domain/ai/weather/dto/TemperatureAndLandForecastDto.kt
  src/main/kotlin/com/back/koreaTravelGuide/domain/ai/weather/dto/parser/DtoParser.kt
  src/main/kotlin/com/back/koreaTravelGuide/domain/ai/weather/service/WeatherService.kt
  src/main/kotlin/com/back/koreaTravelGuide/domain/ai/weather/service/tools/Tools.kt
  src/main/resources/application.yml
Labels: enhancement

#27 feat(be): weather 중기기온 강수 DTO 작업(#26)
  src/main/kotlin/com/back/koreaTravelGuide/KoreaTravelGuideApplication.kt
  src/main/kotlin/com/back/koreaTravelGuide/domain/ai/aiChat/controller/ChatController.kt
  src/main/kotlin/com/back/koreaTravelGuide/domain/ai/weather/dto/LandForecastData.kt
  src/main/kotlin/com/back/koreaTravelGuide/domain/ai/weather/dto/MidForecastDto.kt
  src/main/kotlin/com/back/koreaTravelGuide/domain/ai/weather/dto/TemperatureAndLandForecastDto.kt
  src/main/kotlin/com/back/koreaTravelGuide/domain/ai/weather/dto/TemperatureData.kt
  src/main/kotlin/com/back/koreaTravelGuide/domain/ai/weather/dto/parser/DtoParser.kt
  src/main/kotlin/com/back/koreaTravelGuide/domain/ai/weather/service/WeatherService.kt
  src/main/kotlin/com/back/koreaTravelGuide/domain/ai/weather/service/WeatherServiceCore.kt
  src/test/kotlin/com/back/koreaTravelGuide/WeatherApiRealTest.kt
  src/test/kotlin/com/back/koreaTravelGuide/domain/ai/tour/client/TourApiClientTest.kt
Labels: documentation

#69 Security 리팩토링 및 테스트코드 작성
  src/main/kotlin/com/back/koreaTravelGuide/common/security/CustomOAuth2LoginSuccessHandler.kt
  src/main/kotlin/com/back/koreaTravelGuide/common/security/JwtTokenProvider.kt
  src/main/kotlin/com/back/koreaTravelGuide/common/security/SecurityConfig.kt
  src/main/kotlin/com/back/koreaTravelGuide/domain/user/entity/User.kt
  src/test/kotlin/com/back/koreaTravelGuide/domain/auth/controller/AuthControllerTest.kt
  src/test/kotlin/com/back/koreaTravelGuide/domain/user/controller/UserControllerTest.kt
Labels: refactor
